# comsrv配置文件
service:
  name: "comsrv"
  version: "3.0.0"
  
# Redis配置
redis:
  url: "redis://redis:6379"
  key_prefix: "comsrv:"
  
# 日志配置
logging:
  level: "debug"
  console: true
  file: "/logs/comsrv.log"  # 主日志文件
  
# 性能配置
performance:
  worker_threads: 4
  batch_size: 100
  update_interval_ms: 1000
# 通道配置
channels:
  # Modbus TCP通道 1001 - 电表组1
  - id: 1001
    name: "PowerMeter_Group1"
    protocol_type: "modbus_tcp"
    enabled: true
    protocol_config:
      host: "172.20.0.10"
      port: 502
      timeout_ms: 1000
      batch_read_enabled: true
      max_batch_size: 200
    table_config:
      four_telemetry_route: "ModbusTCP_CH1001"
      four_telemetry_files:
        measurement_file: "measurement.csv"
        signal_file: "signal.csv"
      protocol_mapping_route: "ModbusTCP_CH1001/mappings"
      protocol_mapping_file:
        measurement_mapping: "modbus_measurement.csv"
        signal_mapping: "modbus_signal.csv"
    # 报文日志配置
    message_logging:
      enabled: true
      log_directory: "logs/PowerMeter_Group1"
      log_level: "debug"  # debug记录所有报文，info只记录重要报文
      rotation_policy:
        type: "daily"
        max_files: 30
        max_size_mb: 100
      log_format: "detailed"  # detailed记录完整报文，simple只记录摘要

  # Modbus TCP通道 1002 - 电表组2
  - id: 1002
    name: "PowerMeter_Group2"
    protocol_type: "modbus_tcp"
    enabled: true
    protocol_config:
      host: "172.20.0.10"
      port: 502
      timeout_ms: 1000
      batch_read_enabled: true
      max_batch_size: 150
    table_config:
      four_telemetry_route: "ModbusTCP_CH1002"
      four_telemetry_files:
        measurement_file: "measurement.csv"
        signal_file: "signal.csv"
      protocol_mapping_route: "ModbusTCP_CH1002/mappings"
      protocol_mapping_file:
        measurement_mapping: "modbus_measurement.csv"
        signal_mapping: "modbus_signal.csv"
    message_logging:
      enabled: true
      log_directory: "logs/PowerMeter_Group2"
      log_level: "debug"
      rotation_policy:
        type: "daily"
        max_files: 30
        max_size_mb: 100
      log_format: "detailed"

  # Modbus TCP通道 1003 - 电表组3
  - id: 1003
    name: "PowerMeter_Group3"
    protocol_type: "modbus_tcp"
    enabled: true
    protocol_config:
      host: "172.20.0.11"
      port: 502
      timeout_ms: 1000
      batch_read_enabled: true
      max_batch_size: 180
    table_config:
      four_telemetry_route: "ModbusTCP_CH1003"
      four_telemetry_files:
        measurement_file: "measurement.csv"
        signal_file: "signal.csv"
      protocol_mapping_route: "ModbusTCP_CH1003/mappings"
      protocol_mapping_file:
        measurement_mapping: "modbus_measurement.csv"
        signal_mapping: "modbus_signal.csv"
    message_logging:
      enabled: true
      log_directory: "logs/PowerMeter_Group3"
      log_level: "info"
      rotation_policy:
        type: "daily"
        max_files: 30
        max_size_mb: 100
      log_format: "simple"

  # Modbus TCP通道 1004 - 电表组4
  - id: 1004
    name: "PowerMeter_Group4"
    protocol_type: "modbus_tcp"
    enabled: true
    protocol_config:
      host: "172.20.0.11"
      port: 502
      timeout_ms: 1000
      batch_read_enabled: true
      max_batch_size: 120
    table_config:
      four_telemetry_route: "ModbusTCP_CH1004"
      four_telemetry_files:
        measurement_file: "measurement.csv"
        signal_file: "signal.csv"
      protocol_mapping_route: "ModbusTCP_CH1004/mappings"
      protocol_mapping_file:
        measurement_mapping: "modbus_measurement.csv"
        signal_mapping: "modbus_signal.csv"
    message_logging:
      enabled: true
      log_directory: "logs/PowerMeter_Group4"
      log_level: "info"
      rotation_policy:
        type: "daily"
        max_files: 30
        max_size_mb: 100
      log_format: "simple"

  # Modbus TCP通道 1005 - 变压器组1
  - id: 1005
    name: "Transformer_Group1"
    protocol_type: "modbus_tcp"
    enabled: true
    protocol_config:
      host: "172.20.0.12"
      port: 502
      timeout_ms: 1200
      batch_read_enabled: true
      max_batch_size: 250
    table_config:
      four_telemetry_route: "ModbusTCP_CH1005"
      four_telemetry_files:
        measurement_file: "measurement.csv"
        signal_file: "signal.csv"
      protocol_mapping_route: "ModbusTCP_CH1005/mappings"
      protocol_mapping_file:
        measurement_mapping: "modbus_measurement.csv"
        signal_mapping: "modbus_signal.csv"
    message_logging:
      enabled: true
      log_directory: "logs/Transformer_Group1"
      log_level: "debug"
      rotation_policy:
        type: "daily"
        max_files: 30
        max_size_mb: 200  # 变压器数据更多，日志文件更大
      log_format: "detailed"

  # Modbus TCP通道 1006 - 变压器组2
  - id: 1006
    name: "Transformer_Group2"
    protocol_type: "modbus_tcp"
    enabled: true
    protocol_config:
      host: "172.20.0.12"
      port: 502
      timeout_ms: 1200
      batch_read_enabled: true
      max_batch_size: 200
    table_config:
      four_telemetry_route: "ModbusTCP_CH1006"
      four_telemetry_files:
        measurement_file: "measurement.csv"
        signal_file: "signal.csv"
      protocol_mapping_route: "ModbusTCP_CH1006/mappings"
      protocol_mapping_file:
        measurement_mapping: "modbus_measurement.csv"
        signal_mapping: "modbus_signal.csv"
    message_logging:
      enabled: true
      log_directory: "logs/Transformer_Group2"
      log_level: "debug"
      rotation_policy:
        type: "daily"
        max_files: 30
        max_size_mb: 200
      log_format: "detailed"

  # Modbus RTU通道 2001 - RTU设备组1
  - id: 2001
    name: "RTU_Device_Group1"
    protocol_type: "modbus_rtu"
    enabled: true
    protocol_config:
      port: "/tmp/vserial_master1"
      baudrate: 9600
      data_bits: 8
      stop_bits: 1
      parity: "N"
      timeout_ms: 500
      batch_read_enabled: true
      max_batch_size: 100
    table_config:
      four_telemetry_route: "ModbusRTU_CH2001"
      four_telemetry_files:
        measurement_file: "measurement.csv"
        signal_file: "signal.csv"
      protocol_mapping_route: "ModbusRTU_CH2001/mappings"
      protocol_mapping_file:
        measurement_mapping: "modbus_measurement.csv"
        signal_mapping: "modbus_signal.csv"
    message_logging:
      enabled: true
      log_directory: "logs/RTU_Device_Group1"
      log_level: "debug"
      rotation_policy:
        type: "daily"
        max_files: 14  # RTU设备日志保留时间短
        max_size_mb: 50
      log_format: "detailed"

  # Modbus RTU通道 2002 - RTU设备组2
  - id: 2002
    name: "RTU_Device_Group2"
    protocol_type: "modbus_rtu"
    enabled: true
    protocol_config:
      port: "/tmp/vserial_master2"
      baudrate: 9600
      data_bits: 8
      stop_bits: 1
      parity: "N"
      timeout_ms: 500
      batch_read_enabled: true
      max_batch_size: 80
    table_config:
      four_telemetry_route: "ModbusRTU_CH2002"
      four_telemetry_files:
        measurement_file: "measurement.csv"
        signal_file: "signal.csv"
      protocol_mapping_route: "ModbusRTU_CH2002/mappings"
      protocol_mapping_file:
        measurement_mapping: "modbus_measurement.csv"
        signal_mapping: "modbus_signal.csv"
    message_logging:
      enabled: true
      log_directory: "logs/RTU_Device_Group2"
      log_level: "info"
      rotation_policy:
        type: "daily"
        max_files: 14
        max_size_mb: 50
      log_format: "simple"

# 全局日志配置
logging:
  base_directory: "/opt/comsrv/logs"
  global_level: "info"
  enable_console: true
  enable_file: true
  format: "[%Y-%m-%d %H:%M:%S.%3f] [%l] [%n] %v"