# Product definitions with parent relationships
# Parent relationships represent logical hierarchy, NOT attribute inheritance

products:
  # 站点级 (Station Level)
  station: # Top level - defines station-wide measurements

  # 网关设备 (Gateway Device) - Data collection and control center
  gateway: # Gateway device under station

  # 光伏系统产品 (PV System Products) - All independent
  pv_string: # PV string - basic unit
  pv_combiner: # Combiner box - aggregates multiple strings
  pv_optimizer: # DC optimizer - module-level MPPT
  pv_inverter: # PV inverter - generic (string or central type)
  
  # DC/DC 变换器 (DC/DC Converter) - Independent
  dc_dc_converter: # Standalone DC/DC converter

  # 电池层级 (Battery Hierarchy) - Parent represents containment only
  battery_cell: # Battery cell - smallest unit
  battery_module: battery_cell # Module contains cells
  battery_cluster: battery_module # Cluster contains modules
  battery_stack: battery_cluster # Stack contains clusters
  battery_pack: battery_stack # Pack contains stacks (name unchanged)

  # 其他独立设备 (Other Independent Equipment)
  pcs: # Power Conversion System for energy storage
  diesel_generator: # Diesel generator for backup power
  load: # Generic load (critical or normal type)
  motor: # Industrial motor controller with position/velocity/torque control

# 文件格式说明
# EN: File format description
file_formats:
  measurements_csv:
    description: 测量数据定义（包含T和S类型）
    # EN: Definition of measurement data (includes types T and S)
    columns:
      - id: 序号，从1开始连续编号
      # EN: Sequence number, starting from 1 and incrementing by 1
      - name: 测量点名称
      # EN: Measurement point name
      - unit: 单位（可为空）
      # EN: Unit (optional)

  actions_csv:
    description: 控制动作定义（包含C和A类型）
    # EN: Definition of control actions (includes types C and A)
    columns:
      - id: 序号，从1开始连续编号
      # EN: Sequence number, starting from 1 and incrementing by 1
      - name: 动作名称
      # EN: Action name
      - unit: 单位（可为空，调节类型需要单位）
      # EN: Unit (optional; adjustment type requires a unit)

  properties_csv:
    description: 设备属性模板定义
    # EN: Device property template definitions
    columns:
      - id: 序号，从1开始连续编号
      # EN: Sequence number, starting from 1 and incrementing by 1
      - name: 属性名称
      # EN: Property name
      - unit: 单位（可为空）
      # EN: Unit (optional)
      - description: 中文描述
      # EN: Chinese description

# ModSrv集成说明
# EN: ModSrv integration notes
modsrv_integration:
  description: |
    ModSrv服务需要实现以下功能：
    EN: The ModSrv service needs to implement the following:
    1. 加载config/modsrv/products/下的产品类型定义作为模板
    EN: 1. Load product type definitions under config/modsrv/products/ as templates
    2. 加载config/modsrv/instances.yaml中的设备实例配置
    EN: 2. Load device instance configuration from config/modsrv/instances.yaml
    3. 合并产品模板和实例属性值
    EN: 3. Merge product templates with instance property values
    4. 提供API查询设备的完整定义
    EN: 4. Provide APIs to query the complete device definition

  data_flow:
    1_load_templates: 加载config/modsrv/products/下的产品类型定义
    # EN: Load product type definitions under config/modsrv/products/
    2_load_instances: 加载config/modsrv/instances.yaml
    # EN: Load config/modsrv/instances.yaml
    3_merge_data: 合并模板和实例属性
    # EN: Merge templates and instance properties
    4_serve_api: 提供查询API
    # EN: Provide query APIs
