# ComSrv测试配置 - Docker环境
service:
  name: "comsrv-test"
  api:
    enabled: true
    bind_address: "0.0.0.0:3000"
  
  # Redis配置
  redis:
    enabled: true
    url: "redis://comsrv:comsrv_secure_password_2025@comsrv-redis-test:6379"
    database: 0
    batch_size: 100
    batch_timeout_ms: 50

  # 日志配置
  logging:
    level: "debug"
    file: "/app/logs/comsrv-test.log"
    max_size: 10485760  # 10MB in bytes
    max_files: 5

# CSV配置基础路径
csv_base_path: "/app/config"

# 通道配置
channels:
  # Modbus TCP通道
  - id: 1001
    name: "ModbusTCP_Test_01"
    protocol: "modbus_tcp"
    parameters:
      mode: "tcp"
      host: "comsrv-modbus-tcp-simulator"
      port: 5020
      unit_id: 1
      timeout: 5000
      polling_interval: 2000
    logging:
      level: "debug"
      log_raw_data: true
    table_config:
      four_telemetry_route: "modbus/ModbusTCP_Test_01"
      four_telemetry_files:
        telemetry_file: "telemetry.csv"
        signal_file: "signal.csv"
        control_file: "control.csv"
        adjustment_file: "adjustment.csv"
      protocol_mapping_route: "modbus/ModbusTCP_Test_01"
      protocol_mapping_files:
        telemetry_mapping: "protocol_mapping.csv"
        signal_mapping: "protocol_mapping.csv"
        adjustment_mapping: "protocol_mapping.csv"
        control_mapping: "protocol_mapping.csv"