#!/usr/bin/env python3
import re
import sys
import os

# Translation mapping for Rust files
rust_translations = {
    # Log messages
    '"从默认配置开始构建"': '"Starting from default configuration"',
    '"应用环境变量，前缀: {}"': '"Applying environment variables, prefix: {}"',
    '"加载YAML配置文件: {}"': '"Loading YAML config file: {}"',
    '"YAML配置文件不存在，跳过: {}"': '"YAML config file not found, skipping: {}"',
    '"应用环境变量 {} = {} 到路径 {}"': '"Applying environment variable {} = {} to path {}"',
    # Comments in influxdb/builder.rs
    "//! 线协议构建器": "//! Line Protocol Builder",
    "/// 字段值类型": "/// Field value type",
    "/// `InfluxDB` 线协议构建器": "/// `InfluxDB` Line Protocol Builder",
    "/// 创建新的构建器": "/// Create new builder",
    "/// 添加标签": "/// Add tag",
    "/// 添加字段": "/// Add field",
    "/// 设置时间戳（纳秒）": "/// Set timestamp (nanoseconds)",
    "/// 构建线协议字符串": "/// Build line protocol string",
    "// 测量名称": "// Measurement name",
    "// 标签": "// Tags",
    "// 字段": "// Fields",
    "// 时间戳": "// Timestamp",
    "// 转义函数": "// Escape functions",
    # Common patterns in comments
    "/// 创建": "/// Create",
    "/// 添加": "/// Add",
    "/// 设置": "/// Set",
    "/// 获取": "/// Get",
    "/// 更新": "/// Update",
    "/// 删除": "/// Delete",
    "/// 查询": "/// Query",
    "/// 初始化": "/// Initialize",
    "/// 验证": "/// Validate",
    "/// 检查": "/// Check",
    "/// 处理": "/// Process",
    "/// 执行": "/// Execute",
    "/// 构建": "/// Build",
    "/// 解析": "/// Parse",
    "/// 转换": "/// Convert",
    "/// 清理": "/// Clean",
    "/// 重置": "/// Reset",
    "/// 加载": "/// Load",
    "/// 保存": "/// Save",
    "/// 发送": "/// Send",
    "/// 接收": "/// Receive",
    "/// 连接": "/// Connect",
    "/// 断开": "/// Disconnect",
    "/// 启动": "/// Start",
    "/// 停止": "/// Stop",
    "/// 错误": "/// Error",
    "/// 成功": "/// Success",
    "/// 失败": "/// Failed",
    "/// 状态": "/// Status",
    "/// 配置": "/// Configuration",
    "/// 参数": "/// Parameter",
    "/// 结果": "/// Result",
    "/// 返回": "/// Return",
    "/// 函数": "/// Function",
    "/// 方法": "/// Method",
    "/// 字段": "/// Field",
    "/// 属性": "/// Property",
    "/// 类型": "/// Type",
    "/// 实现": "/// Implementation",
    "/// 示例": "/// Example",
    "/// 注意": "/// Note",
    "/// 警告": "/// Warning",
    # Common phrases
    "成功": "success",
    "失败": "failed",
    "错误": "error",
    "警告": "warning",
    "信息": "info",
    "调试": "debug",
    "启动": "start",
    "停止": "stop",
    "运行中": "running",
    "已停止": "stopped",
    "连接": "connect",
    "断开": "disconnect",
    "重试": "retry",
    "超时": "timeout",
    "取消": "cancel",
    "完成": "complete",
    "等待": "waiting",
    "处理中": "processing",
    "已完成": "completed",
    "未完成": "incomplete",
    "初始化": "initialize",
    "配置": "configuration",
    "服务": "service",
    "客户端": "client",
    "服务器": "server",
    "请求": "request",
    "响应": "response",
    "数据": "data",
    "消息": "message",
    "事件": "event",
    "通道": "channel",
    "缓冲区": "buffer",
    "队列": "queue",
    "线程": "thread",
    "进程": "process",
    "任务": "task",
    "作业": "job",
    "定时器": "timer",
    "计数器": "counter",
    "统计": "statistics",
    "指标": "metrics",
    "日志": "log",
    "追踪": "trace",
    "监控": "monitor",
    "告警": "alarm",
    "通知": "notification",
    "报告": "report",
    "分析": "analysis",
    "优化": "optimize",
    "性能": "performance",
    "资源": "resource",
    "内存": "memory",
    "存储": "storage",
    "网络": "network",
    "协议": "protocol",
    "编码": "encode",
    "解码": "decode",
    "加密": "encrypt",
    "解密": "decrypt",
    "认证": "authentication",
    "授权": "authorization",
    "权限": "permission",
    "用户": "user",
    "角色": "role",
    "会话": "session",
    "令牌": "token",
    "密钥": "key",
    "证书": "certificate",
    "签名": "signature",
    "验证": "verify",
    "校验": "validate",
    "测试": "test",
    "调试": "debug",
    "发布": "release",
    "部署": "deploy",
    "更新": "update",
    "升级": "upgrade",
    "回滚": "rollback",
    "备份": "backup",
    "恢复": "restore",
    "导入": "import",
    "导出": "export",
    "同步": "sync",
    "异步": "async",
    "并发": "concurrent",
    "并行": "parallel",
    "串行": "serial",
    "阻塞": "blocking",
    "非阻塞": "non-blocking",
    "超时": "timeout",
    "重试": "retry",
    "回调": "callback",
    "事件": "event",
    "触发": "trigger",
    "监听": "listen",
    "广播": "broadcast",
    "订阅": "subscribe",
    "发布": "publish",
    "推送": "push",
    "拉取": "pull",
    "上传": "upload",
    "下载": "download",
    "复制": "copy",
    "移动": "move",
    "删除": "delete",
    "创建": "create",
    "读取": "read",
    "写入": "write",
    "打开": "open",
    "关闭": "close",
    "保存": "save",
    "加载": "load",
    "刷新": "refresh",
    "重载": "reload",
    "清空": "clear",
    "重置": "reset",
    "格式化": "format",
    "解析": "parse",
    "编译": "compile",
    "构建": "build",
    "打包": "package",
    "安装": "install",
    "卸载": "uninstall",
    "启用": "enable",
    "禁用": "disable",
    "激活": "activate",
    "停用": "deactivate",
    "挂起": "suspend",
    "恢复": "resume",
    "中断": "interrupt",
    "继续": "continue",
    "暂停": "pause",
    "开始": "start",
    "结束": "end",
    "完成": "finish",
    "取消": "cancel",
    "确认": "confirm",
    "拒绝": "reject",
    "允许": "allow",
    "禁止": "forbid",
    "成功": "success",
    "失败": "failure",
    "错误": "error",
    "异常": "exception",
    "警告": "warning",
    "提示": "hint",
    "信息": "info",
    "详情": "details",
    "摘要": "summary",
    "列表": "list",
    "集合": "collection",
    "数组": "array",
    "映射": "map",
    "键": "key",
    "值": "value",
    "对": "pair",
    "元素": "element",
    "节点": "node",
    "链接": "link",
    "路径": "path",
    "目录": "directory",
    "文件": "file",
    "文件夹": "folder",
    "扩展": "extension",
    "名称": "name",
    "标识": "identifier",
    "描述": "description",
    "说明": "description",
    "备注": "remark",
    "注释": "comment",
    "文档": "document",
    "帮助": "help",
    "手册": "manual",
    "指南": "guide",
    "教程": "tutorial",
    "示例": "example",
    "演示": "demo",
    "测试": "test",
    "基准": "benchmark",
    "性能": "performance",
    "优化": "optimization",
    "改进": "improvement",
    "修复": "fix",
    "补丁": "patch",
    "版本": "version",
    "发布": "release",
    "更新": "update",
    "变更": "change",
    "日志": "log",
    "历史": "history",
    "记录": "record",
    "跟踪": "track",
    "监控": "monitor",
    "分析": "analyze",
    "统计": "statistics",
    "报表": "report",
    "图表": "chart",
    "仪表盘": "dashboard",
    "指标": "metric",
    "阈值": "threshold",
    "限制": "limit",
    "配额": "quota",
    "容量": "capacity",
    "大小": "size",
    "长度": "length",
    "宽度": "width",
    "高度": "height",
    "深度": "depth",
    "距离": "distance",
    "时间": "time",
    "日期": "date",
    "时刻": "moment",
    "周期": "period",
    "间隔": "interval",
    "延迟": "delay",
    "持续": "duration",
    "频率": "frequency",
    "速率": "rate",
    "速度": "speed",
    "吞吐量": "throughput",
    "带宽": "bandwidth",
    "流量": "traffic",
    "负载": "load",
    "压力": "pressure",
    "容量": "capacity",
    "资源": "resource",
    "设备": "device",
    "硬件": "hardware",
    "软件": "software",
    "系统": "system",
    "平台": "platform",
    "框架": "framework",
    "库": "library",
    "模块": "module",
    "组件": "component",
    "插件": "plugin",
    "扩展": "extension",
    "接口": "interface",
    "端口": "port",
    "地址": "address",
    "主机": "host",
    "域名": "domain",
    "路由": "route",
    "网关": "gateway",
    "代理": "proxy",
    "防火墙": "firewall",
    "负载均衡": "load balance",
    "集群": "cluster",
    "节点": "node",
    "实例": "instance",
    "副本": "replica",
    "主": "master",
    "从": "slave",
    "备份": "backup",
    "恢复": "recovery",
    "故障": "failure",
    "异常": "exception",
    "告警": "alarm",
    "通知": "notification",
    "消息": "message",
    "邮件": "email",
    "短信": "sms",
    "推送": "push",
    "订阅": "subscription",
    "发布": "publication",
    "队列": "queue",
    "主题": "topic",
    "分区": "partition",
    "偏移": "offset",
    "批次": "batch",
    "事务": "transaction",
    "提交": "commit",
    "回滚": "rollback",
    "锁": "lock",
    "解锁": "unlock",
    "同步": "synchronize",
    "异步": "asynchronous",
    "并发": "concurrent",
    "并行": "parallel",
    "串行": "serial",
    "顺序": "sequence",
    "随机": "random",
    "循环": "loop",
    "迭代": "iterate",
    "递归": "recursive",
    "条件": "condition",
    "判断": "judge",
    "选择": "select",
    "过滤": "filter",
    "排序": "sort",
    "分组": "group",
    "聚合": "aggregate",
    "计算": "calculate",
    "统计": "statistics",
    "求和": "sum",
    "平均": "average",
    "最大": "maximum",
    "最小": "minimum",
    "计数": "count",
    "合并": "merge",
    "拆分": "split",
    "转换": "transform",
    "映射": "mapping",
    "编码": "encode",
    "解码": "decode",
    "压缩": "compress",
    "解压": "decompress",
    "加密": "encrypt",
    "解密": "decrypt",
    "签名": "sign",
    "验证": "verify",
    "哈希": "hash",
    "摘要": "digest",
    "校验和": "checksum",
    "标识符": "identifier",
    "唯一": "unique",
    "主键": "primary key",
    "外键": "foreign key",
    "索引": "index",
    "约束": "constraint",
    "规则": "rule",
    "策略": "policy",
    "算法": "algorithm",
    "逻辑": "logic",
    "流程": "flow",
    "步骤": "step",
    "阶段": "stage",
    "状态": "state",
    "模式": "mode",
    "类型": "type",
    "类别": "category",
    "级别": "level",
    "优先级": "priority",
    "权重": "weight",
    "分数": "score",
    "评分": "rating",
    "等级": "grade",
    "标签": "tag",
    "标记": "mark",
    "标志": "flag",
    "属性": "attribute",
    "特性": "feature",
    "功能": "function",
    "能力": "capability",
    "权限": "permission",
    "角色": "role",
    "用户": "user",
    "组": "group",
    "团队": "team",
    "组织": "organization",
    "部门": "department",
    "项目": "project",
    "任务": "task",
    "工作": "work",
    "作业": "job",
    "活动": "activity",
    "事件": "event",
    "操作": "operation",
    "动作": "action",
    "行为": "behavior",
    "处理": "process",
    "执行": "execute",
    "运行": "run",
    "调用": "call",
    "请求": "request",
    "响应": "response",
    "返回": "return",
    "结果": "result",
    "输出": "output",
    "输入": "input",
    "参数": "parameter",
    "变量": "variable",
    "常量": "constant",
    "配置": "config",
    "设置": "setting",
    "选项": "option",
    "默认": "default",
    "自定义": "custom",
    "扩展": "extend",
    "继承": "inherit",
    "实现": "implement",
    "接口": "interface",
    "抽象": "abstract",
    "具体": "concrete",
    "实例": "instance",
    "对象": "object",
    "类": "class",
    "结构": "struct",
    "枚举": "enum",
    "特征": "trait",
    "模块": "module",
    "包": "package",
    "库": "library",
    "依赖": "dependency",
    "引用": "reference",
    "导入": "import",
    "导出": "export",
    "公开": "public",
    "私有": "private",
    "保护": "protected",
    "内部": "internal",
    "外部": "external",
    "全局": "global",
    "局部": "local",
    "静态": "static",
    "动态": "dynamic",
    "常量": "constant",
    "变量": "variable",
    "可变": "mutable",
    "不可变": "immutable",
    "引用": "reference",
    "借用": "borrow",
    "所有权": "ownership",
    "生命周期": "lifetime",
    "作用域": "scope",
    "闭包": "closure",
    "泛型": "generic",
    "约束": "constraint",
    "边界": "bound",
    "关联": "associated",
    "别名": "alias",
    "宏": "macro",
    "属性": "attribute",
    "注解": "annotation",
    "元数据": "metadata",
    "文档": "documentation",
    "注释": "comment",
    "说明": "description",
    "描述": "description",
    "定义": "definition",
    "声明": "declaration",
    "表达式": "expression",
    "语句": "statement",
    "块": "block",
    "函数": "function",
    "方法": "method",
    "过程": "procedure",
    "子程序": "subroutine",
    "回调": "callback",
    "闭包": "closure",
    "匿名": "anonymous",
    "命名": "named",
    "参数": "parameter",
    "返回值": "return value",
    "异常": "exception",
    "错误": "error",
    "成功": "success",
    "失败": "failure",
    "结果": "result",
    "选项": "option",
    "可能": "maybe",
    "某些": "some",
    "没有": "none",
    "空": "empty",
    "无": "null",
    "真": "true",
    "假": "false",
    "是": "yes",
    "否": "no",
    "开": "on",
    "关": "off",
    "启用": "enabled",
    "禁用": "disabled",
    "活动": "active",
    "非活动": "inactive",
    "有效": "valid",
    "无效": "invalid",
    "可用": "available",
    "不可用": "unavailable",
    "存在": "exists",
    "不存在": "not exists",
    "包含": "contains",
    "排除": "excludes",
    "匹配": "match",
    "不匹配": "not match",
    "相等": "equal",
    "不等": "not equal",
    "大于": "greater than",
    "小于": "less than",
    "大于等于": "greater than or equal",
    "小于等于": "less than or equal",
    "之间": "between",
    "范围": "range",
    "区间": "interval",
    "边界": "boundary",
    "限制": "limit",
    "最大": "max",
    "最小": "min",
    "平均": "avg",
    "总和": "sum",
    "计数": "count",
    "数量": "quantity",
    "总数": "total",
    "部分": "partial",
    "全部": "all",
    "任意": "any",
    "每个": "each",
    "所有": "all",
    "没有": "none",
    "其他": "other",
    "剩余": "remaining",
    "额外": "extra",
    "附加": "additional",
    "默认": "default",
    "自定义": "custom",
    "标准": "standard",
    "扩展": "extended",
    "基本": "basic",
    "高级": "advanced",
    "简单": "simple",
    "复杂": "complex",
    "普通": "normal",
    "特殊": "special",
    "常规": "regular",
    "异常": "abnormal",
    "正常": "normal",
    "错误": "error",
    "警告": "warning",
    "信息": "info",
    "调试": "debug",
    "跟踪": "trace",
    "致命": "fatal",
    "严重": "critical",
    "主要": "major",
    "次要": "minor",
    "轻微": "trivial",
    "紧急": "urgent",
    "重要": "important",
    "一般": "general",
    "低": "low",
    "中": "medium",
    "高": "high",
    "非常高": "very high",
    "极高": "extremely high",
    "无": "none",
    "未知": "unknown",
    "待定": "pending",
    "进行中": "in progress",
    "已完成": "completed",
    "已取消": "cancelled",
    "已暂停": "paused",
    "已停止": "stopped",
    "已启动": "started",
    "就绪": "ready",
    "忙碌": "busy",
    "空闲": "idle",
    "等待": "waiting",
    "运行": "running",
    "睡眠": "sleeping",
    "唤醒": "waking",
    "挂起": "suspended",
    "恢复": "resumed",
    "初始化": "initializing",
    "终止": "terminating",
    "清理": "cleaning",
    "准备": "preparing",
    "加载": "loading",
    "保存": "saving",
    "同步": "syncing",
    "备份": "backing up",
    "恢复": "restoring",
    "升级": "upgrading",
    "降级": "downgrading",
    "安装": "installing",
    "卸载": "uninstalling",
    "配置": "configuring",
    "重配置": "reconfiguring",
    "启动": "starting",
    "停止": "stopping",
    "重启": "restarting",
    "刷新": "refreshing",
    "更新": "updating",
    "检查": "checking",
    "验证": "validating",
    "测试": "testing",
    "监控": "monitoring",
    "记录": "recording",
    "报告": "reporting",
    "分析": "analyzing",
    "优化": "optimizing",
    "调整": "adjusting",
    "修复": "fixing",
    "改进": "improving",
    "增强": "enhancing",
    "扩展": "extending",
    "缩减": "reducing",
    "限制": "limiting",
    "控制": "controlling",
    "管理": "managing",
    "维护": "maintaining",
    "支持": "supporting",
    "服务": "serving",
    "处理": "handling",
    "响应": "responding",
    "通信": "communicating",
    "传输": "transferring",
    "接收": "receiving",
    "发送": "sending",
    "广播": "broadcasting",
    "多播": "multicasting",
    "单播": "unicasting",
    "路由": "routing",
    "转发": "forwarding",
    "过滤": "filtering",
    "拦截": "intercepting",
    "代理": "proxying",
    "缓存": "caching",
    "存储": "storing",
    "检索": "retrieving",
    "查询": "querying",
    "搜索": "searching",
    "索引": "indexing",
    "排序": "sorting",
    "分页": "paging",
    "分组": "grouping",
    "聚合": "aggregating",
    "统计": "counting",
    "计算": "computing",
    "评估": "evaluating",
    "分析": "analyzing",
    "处理": "processing",
    "转换": "converting",
    "编码": "encoding",
    "解码": "decoding",
    "序列化": "serializing",
    "反序列化": "deserializing",
    "压缩": "compressing",
    "解压": "decompressing",
    "打包": "packing",
    "解包": "unpacking",
    "合并": "merging",
    "分割": "splitting",
    "连接": "joining",
    "断开": "disconnecting",
    "绑定": "binding",
    "解绑": "unbinding",
    "关联": "associating",
    "分离": "dissociating",
    "附加": "attaching",
    "分离": "detaching",
    "挂载": "mounting",
    "卸载": "unmounting",
    "映射": "mapping",
    "取消映射": "unmapping",
    "分配": "allocating",
    "释放": "deallocating",
    "保留": "reserving",
    "释放": "releasing",
    "获取": "acquiring",
    "释放": "releasing",
    "占用": "occupying",
    "空闲": "freeing",
    "使用": "using",
    "停用": "disusing",
    "激活": "activating",
    "停用": "deactivating",
    "启用": "enabling",
    "禁用": "disabling",
    "允许": "allowing",
    "拒绝": "denying",
    "授权": "authorizing",
    "撤销": "revoking",
    "批准": "approving",
    "拒绝": "rejecting",
    "接受": "accepting",
    "拒绝": "declining",
    "确认": "confirming",
    "取消": "cancelling",
    "提交": "submitting",
    "撤回": "withdrawing",
    "发布": "publishing",
    "撤销": "unpublishing",
    "订阅": "subscribing",
    "退订": "unsubscribing",
    "注册": "registering",
    "注销": "unregistering",
    "登录": "logging in",
    "登出": "logging out",
    "认证": "authenticating",
    "授权": "authorizing",
    "验证": "verifying",
    "校验": "validating",
    "签名": "signing",
    "验签": "verifying signature",
    "加密": "encrypting",
    "解密": "decrypting",
    "编码": "encoding",
    "解码": "decoding",
    "转换": "converting",
    "翻译": "translating",
    "解释": "interpreting",
    "编译": "compiling",
    "链接": "linking",
    "加载": "loading",
    "执行": "executing",
    "调试": "debugging",
    "测试": "testing",
    "分析": "profiling",
    "优化": "optimizing",
    "重构": "refactoring",
    "格式化": "formatting",
    "清理": "cleaning",
    "构建": "building",
    "打包": "packaging",
    "发布": "releasing",
    "部署": "deploying",
    "安装": "installing",
    "配置": "configuring",
    "初始化": "initializing",
    "启动": "starting",
    "运行": "running",
    "监控": "monitoring",
    "维护": "maintaining",
    "更新": "updating",
    "升级": "upgrading",
    "修复": "patching",
    "回滚": "rolling back",
    "备份": "backing up",
    "恢复": "restoring",
    "迁移": "migrating",
    "同步": "synchronizing",
    "复制": "replicating",
    "分发": "distributing",
    "负载均衡": "load balancing",
    "故障转移": "failing over",
    "容错": "fault tolerance",
    "高可用": "high availability",
    "扩展": "scaling",
    "伸缩": "elasticity",
    "集群": "clustering",
    "分片": "sharding",
    "分区": "partitioning",
    "复制": "replication",
    "同步": "synchronization",
    "一致性": "consistency",
    "可用性": "availability",
    "分区容错": "partition tolerance",
    "事务": "transaction",
    "隔离": "isolation",
    "持久性": "durability",
    "原子性": "atomicity",
    "一致性": "consistency",
    "并发": "concurrency",
    "并行": "parallelism",
    "异步": "asynchrony",
    "同步": "synchrony",
    "阻塞": "blocking",
    "非阻塞": "non-blocking",
    "死锁": "deadlock",
    "饥饿": "starvation",
    "竞态": "race condition",
    "互斥": "mutual exclusion",
    "信号量": "semaphore",
    "条件变量": "condition variable",
    "屏障": "barrier",
    "读写锁": "read-write lock",
    "自旋锁": "spin lock",
    "乐观锁": "optimistic lock",
    "悲观锁": "pessimistic lock",
    "分布式锁": "distributed lock",
    "租约": "lease",
    "时钟": "clock",
    "时间戳": "timestamp",
    "向量时钟": "vector clock",
    "逻辑时钟": "logical clock",
    "物理时钟": "physical clock",
    "同步时钟": "synchronized clock",
    "漂移": "drift",
    "偏差": "skew",
    "延迟": "latency",
    "吞吐": "throughput",
    "带宽": "bandwidth",
    "容量": "capacity",
    "利用率": "utilization",
    "饱和度": "saturation",
    "队列": "queue",
    "缓冲": "buffer",
    "缓存": "cache",
    "存储": "storage",
    "内存": "memory",
    "磁盘": "disk",
    "网络": "network",
    "文件系统": "file system",
    "数据库": "database",
    "表": "table",
    "行": "row",
    "列": "column",
    "字段": "field",
    "记录": "record",
    "索引": "index",
    "主键": "primary key",
    "外键": "foreign key",
    "约束": "constraint",
    "触发器": "trigger",
    "存储过程": "stored procedure",
    "视图": "view",
    "函数": "function",
    "查询": "query",
    "插入": "insert",
    "更新": "update",
    "删除": "delete",
    "选择": "select",
    "连接": "join",
    "并集": "union",
    "交集": "intersection",
    "差集": "difference",
    "笛卡尔积": "cartesian product",
    "投影": "projection",
    "选择": "selection",
    "聚合": "aggregation",
    "分组": "grouping",
    "排序": "ordering",
    "限制": "limiting",
    "偏移": "offsetting",
    "分页": "pagination",
    "游标": "cursor",
    "批处理": "batch processing",
    "流处理": "stream processing",
    "实时": "real-time",
    "离线": "offline",
    "在线": "online",
    "热": "hot",
    "冷": "cold",
    "温": "warm",
    "活跃": "active",
    "空闲": "idle",
    "繁忙": "busy",
    "阻塞": "blocked",
    "等待": "waiting",
    "运行": "running",
    "完成": "completed",
    "失败": "failed",
    "超时": "timeout",
    "取消": "cancelled",
    "中止": "aborted",
    "成功": "succeeded",
    "错误": "error",
    "异常": "exception",
    "故障": "fault",
    "崩溃": "crash",
    "恢复": "recovery",
    "重试": "retry",
    "回退": "fallback",
    "降级": "degrade",
    "熔断": "circuit break",
    "限流": "rate limit",
    "排队": "queue",
    "缓冲": "buffer",
    "批量": "batch",
    "合并": "merge",
    "拆分": "split",
    "路由": "route",
    "分发": "dispatch",
    "调度": "schedule",
    "编排": "orchestrate",
    "协调": "coordinate",
    "同步": "synchronize",
    "通信": "communicate",
    "消息": "message",
    "事件": "event",
    "信号": "signal",
    "通知": "notification",
    "请求": "request",
    "响应": "response",
    "回复": "reply",
    "确认": "acknowledge",
    "握手": "handshake",
    "心跳": "heartbeat",
    "超时": "timeout",
    "重传": "retransmit",
    "丢失": "lost",
    "重复": "duplicate",
    "乱序": "out of order",
    "分片": "fragment",
    "重组": "reassemble",
    "校验": "checksum",
    "纠错": "error correction",
    "压缩": "compression",
    "加密": "encryption",
    "认证": "authentication",
    "授权": "authorization",
    "会话": "session",
    "连接": "connection",
    "断开": "disconnection",
    "重连": "reconnection",
    "保活": "keep alive",
    "空闲": "idle",
    "活跃": "active",
    "关闭": "close",
    "打开": "open",
    "监听": "listen",
    "接受": "accept",
    "拒绝": "reject",
    "转发": "forward",
    "重定向": "redirect",
    "代理": "proxy",
    "网关": "gateway",
    "路由器": "router",
    "交换机": "switch",
    "集线器": "hub",
    "网桥": "bridge",
    "防火墙": "firewall",
    "负载均衡器": "load balancer",
    "反向代理": "reverse proxy",
    "正向代理": "forward proxy",
    "透明代理": "transparent proxy",
    "缓存代理": "caching proxy",
    "应用网关": "application gateway",
    "API网关": "API gateway",
    "服务网格": "service mesh",
    "边缘计算": "edge computing",
    "云计算": "cloud computing",
    "雾计算": "fog computing",
    "分布式": "distributed",
    "集中式": "centralized",
    "去中心化": "decentralized",
    "联邦": "federated",
    "对等": "peer-to-peer",
    "主从": "master-slave",
    "客户端服务器": "client-server",
    "发布订阅": "publish-subscribe",
    "请求响应": "request-response",
    "推": "push",
    "拉": "pull",
    "流": "stream",
    "批": "batch",
    "实时": "real-time",
    "近实时": "near real-time",
    "异步": "asynchronous",
    "同步": "synchronous",
    "回调": "callback",
    "承诺": "promise",
    "未来": "future",
    "协程": "coroutine",
    "线程": "thread",
    "进程": "process",
    "任务": "task",
    "作业": "job",
    "工作流": "workflow",
    "管道": "pipeline",
    "链": "chain",
    "图": "graph",
    "树": "tree",
    "森林": "forest",
    "节点": "node",
    "边": "edge",
    "顶点": "vertex",
    "路径": "path",
    "环": "cycle",
    "连通": "connected",
    "断开": "disconnected",
    "有向": "directed",
    "无向": "undirected",
    "权重": "weight",
    "距离": "distance",
    "最短路径": "shortest path",
    "生成树": "spanning tree",
    "拓扑排序": "topological sort",
    "深度优先": "depth first",
    "广度优先": "breadth first",
    "贪婪": "greedy",
    "动态规划": "dynamic programming",
    "分治": "divide and conquer",
    "回溯": "backtracking",
    "分支限界": "branch and bound",
    "启发式": "heuristic",
    "元启发式": "metaheuristic",
    "随机": "random",
    "确定性": "deterministic",
    "概率": "probabilistic",
    "模糊": "fuzzy",
    "神经": "neural",
    "遗传": "genetic",
    "进化": "evolutionary",
    "群体": "swarm",
    "粒子": "particle",
    "蚁群": "ant colony",
    "模拟退火": "simulated annealing",
    "禁忌搜索": "tabu search",
    "局部搜索": "local search",
    "全局搜索": "global search",
    "最优": "optimal",
    "次优": "suboptimal",
    "可行": "feasible",
    "不可行": "infeasible",
    "约束": "constraint",
    "目标": "objective",
    "优化": "optimization",
    "最大化": "maximization",
    "最小化": "minimization",
    "线性": "linear",
    "非线性": "nonlinear",
    "凸": "convex",
    "非凸": "non-convex",
    "连续": "continuous",
    "离散": "discrete",
    "整数": "integer",
    "二进制": "binary",
    "混合": "mixed",
    "多目标": "multi-objective",
    "单目标": "single-objective",
    "约束": "constrained",
    "无约束": "unconstrained",
    "可行域": "feasible region",
    "边界": "boundary",
    "内部": "interior",
    "外部": "exterior",
    "梯度": "gradient",
    "海森": "hessian",
    "拉格朗日": "lagrangian",
    "对偶": "dual",
    "原始": "primal",
    "松弛": "relaxation",
    "分解": "decomposition",
    "聚合": "aggregation",
    "近似": "approximation",
    "精确": "exact",
    "启发": "heuristic",
    "元": "meta",
    "混合": "hybrid",
    "并行": "parallel",
    "分布": "distributed",
    "集中": "centralized",
    "分散": "decentralized",
    "层次": "hierarchical",
    "扁平": "flat",
    "模块": "modular",
    "整体": "monolithic",
    "微服务": "microservice",
    "单体": "monolith",
    "容器": "container",
    "虚拟机": "virtual machine",
    "裸机": "bare metal",
    "云": "cloud",
    "边缘": "edge",
    "本地": "on-premise",
    "混合云": "hybrid cloud",
    "多云": "multi-cloud",
    "私有云": "private cloud",
    "公有云": "public cloud",
    "社区云": "community cloud",
    "基础设施即服务": "infrastructure as a service",
    "平台即服务": "platform as a service",
    "软件即服务": "software as a service",
    "函数即服务": "function as a service",
    "后端即服务": "backend as a service",
    "数据库即服务": "database as a service",
    "容器即服务": "container as a service",
    "无服务器": "serverless",
    "事件驱动": "event-driven",
    "消息驱动": "message-driven",
    "数据驱动": "data-driven",
    "模型驱动": "model-driven",
    "领域驱动": "domain-driven",
    "测试驱动": "test-driven",
    "行为驱动": "behavior-driven",
    "敏捷": "agile",
    "瀑布": "waterfall",
    "迭代": "iterative",
    "增量": "incremental",
    "螺旋": "spiral",
    "原型": "prototype",
    "快速": "rapid",
    "极限编程": "extreme programming",
    "Scrum": "Scrum",
    "看板": "Kanban",
    "精益": "lean",
    "持续集成": "continuous integration",
    "持续交付": "continuous delivery",
    "持续部署": "continuous deployment",
    "DevOps": "DevOps",
    "DevSecOps": "DevSecOps",
    "GitOps": "GitOps",
    "MLOps": "MLOps",
    "DataOps": "DataOps",
    "AIOps": "AIOps",
    "基础设施即代码": "infrastructure as code",
    "配置即代码": "configuration as code",
    "策略即代码": "policy as code",
    "安全即代码": "security as code",
    "合规即代码": "compliance as code",
    "文档即代码": "documentation as code",
    "测试即代码": "test as code",
    "监控即代码": "monitoring as code",
    "可观测性": "observability",
    "日志": "logging",
    "指标": "metrics",
    "追踪": "tracing",
    "告警": "alerting",
    "仪表板": "dashboard",
    "可视化": "visualization",
    "报表": "reporting",
    "分析": "analytics",
    "洞察": "insights",
    "预测": "prediction",
    "异常检测": "anomaly detection",
    "根因分析": "root cause analysis",
    "容量规划": "capacity planning",
    "性能调优": "performance tuning",
    "故障排查": "troubleshooting",
    "事后分析": "post-mortem",
    "灾难恢复": "disaster recovery",
    "业务连续性": "business continuity",
    "高可用性": "high availability",
    "容错性": "fault tolerance",
    "弹性": "resilience",
    "可靠性": "reliability",
    "可用性": "availability",
    "可维护性": "maintainability",
    "可扩展性": "scalability",
    "可移植性": "portability",
    "互操作性": "interoperability",
    "兼容性": "compatibility",
    "向后兼容": "backward compatibility",
    "向前兼容": "forward compatibility",
    "版本控制": "version control",
    "语义化版本": "semantic versioning",
    "变更管理": "change management",
    "发布管理": "release management",
    "配置管理": "configuration management",
    "依赖管理": "dependency management",
    "包管理": "package management",
    "模块管理": "module management",
    "代码审查": "code review",
    "静态分析": "static analysis",
    "动态分析": "dynamic analysis",
    "代码覆盖": "code coverage",
    "测试覆盖": "test coverage",
    "单元测试": "unit test",
    "集成测试": "integration test",
    "系统测试": "system test",
    "验收测试": "acceptance test",
    "回归测试": "regression test",
    "冒烟测试": "smoke test",
    "负载测试": "load test",
    "压力测试": "stress test",
    "性能测试": "performance test",
    "安全测试": "security test",
    "渗透测试": "penetration test",
    "模糊测试": "fuzz test",
    "混沌工程": "chaos engineering",
    "故障注入": "fault injection",
    "A/B测试": "A/B test",
    "金丝雀发布": "canary release",
    "蓝绿部署": "blue-green deployment",
    "滚动更新": "rolling update",
    "灰度发布": "gray release",
    "特性开关": "feature toggle",
    "特性标志": "feature flag",
    "实验": "experiment",
    "假设": "hypothesis",
    "验证": "validation",
    "度量": "measurement",
    "基准": "baseline",
    "目标": "target",
    "阈值": "threshold",
    "趋势": "trend",
    "模式": "pattern",
    "异常": "anomaly",
    "偏差": "deviation",
    "方差": "variance",
    "标准差": "standard deviation",
    "均值": "mean",
    "中位数": "median",
    "众数": "mode",
    "百分位": "percentile",
    "四分位": "quartile",
    "直方图": "histogram",
    "散点图": "scatter plot",
    "折线图": "line chart",
    "柱状图": "bar chart",
    "饼图": "pie chart",
    "热力图": "heatmap",
    "树图": "treemap",
    "桑基图": "sankey diagram",
    "甘特图": "gantt chart",
    "网络图": "network diagram",
    "流程图": "flowchart",
    "时序图": "sequence diagram",
    "类图": "class diagram",
    "组件图": "component diagram",
    "部署图": "deployment diagram",
    "用例图": "use case diagram",
    "活动图": "activity diagram",
    "状态图": "state diagram",
    "协作图": "collaboration diagram",
    "对象图": "object diagram",
    "包图": "package diagram",
    "组合结构图": "composite structure diagram",
    "轮廓图": "profile diagram",
    "时间图": "timing diagram",
    "交互概览图": "interaction overview diagram",
    "通信图": "communication diagram",
}


def translate_file(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    original_content = content

    # Replace all known translations
    for chinese, english in rust_translations.items():
        content = content.replace(chinese, english)

    # Find any remaining Chinese characters (excluding those in test data or examples)
    chinese_pattern = re.compile(r"[\u4e00-\u9fa5]+")
    lines = content.split("\n")
    remaining = []

    for i, line in enumerate(lines):
        # Skip lines that look like test data or example strings
        if (
            "test" in line.lower()
            or "example" in line.lower()
            or "#[cfg(test)]" in line
            or "mod tests" in line
        ):
            continue

        matches = chinese_pattern.findall(line)
        if matches:
            for match in matches:
                if match not in [v for v in rust_translations.values()]:
                    remaining.append((i + 1, match, line.strip()))

    if remaining:
        print(f"Warning: Found untranslated Chinese text in {filepath}:")
        seen = set()
        for line_no, text, context in remaining:
            if text not in seen:
                print(f"  Line {line_no}: {text}")
                print(f"    Context: {context[:80]}...")
                seen.add(text)

    # Only write if content changed
    if content != original_content:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Translated {filepath}")
    else:
        print(f"No changes needed for {filepath}")

    return content


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python translate_rust.py <file_or_directory>")
        sys.exit(1)

    path = sys.argv[1]

    if os.path.isfile(path):
        translate_file(path)
    elif os.path.isdir(path):
        # Find all .rs files
        for root, dirs, files in os.walk(path):
            # Skip target and hidden directories
            dirs[:] = [d for d in dirs if not d.startswith(".") and d != "target"]

            for file in files:
                if file.endswith(".rs"):
                    filepath = os.path.join(root, file)
                    translate_file(filepath)
    else:
        print(f"Error: {path} is not a valid file or directory")
        sys.exit(1)
