// This file is @generated by prost-build.
/// 基础消息定义
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Empty {}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PluginInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub protocol_type: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub supported_features: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "5")]
    pub metadata:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub raw_data: ::prost::alloc::vec::Vec<u8>,
    /// 通道配置等上下文信息
    #[prost(map = "string, string", tag = "2")]
    pub context:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseResponse {
    #[prost(message, repeated, tag = "1")]
    pub points: ::prost::alloc::vec::Vec<PointData>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PointData {
    #[prost(uint32, tag = "1")]
    pub point_id: u32,
    #[prost(int64, tag = "6")]
    pub timestamp: i64,
    /// 数据质量标志
    #[prost(uint32, tag = "7")]
    pub quality: u32,
    #[prost(oneof = "point_data::Value", tags = "2, 3, 4, 5")]
    pub value: ::core::option::Option<point_data::Value>,
}
/// Nested message and enum types in `PointData`.
pub mod point_data {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(double, tag = "2")]
        FloatValue(f64),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(bool, tag = "4")]
        BoolValue(bool),
        #[prost(string, tag = "5")]
        StringValue(::prost::alloc::string::String),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommandValue {
    #[prost(oneof = "command_value::Value", tags = "1, 2, 3, 4")]
    pub value: ::core::option::Option<command_value::Value>,
}
/// Nested message and enum types in `CommandValue`.
pub mod command_value {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(double, tag = "1")]
        FloatValue(f64),
        #[prost(int64, tag = "2")]
        IntValue(i64),
        #[prost(bool, tag = "3")]
        BoolValue(bool),
        #[prost(string, tag = "4")]
        StringValue(::prost::alloc::string::String),
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncodeRequest {
    #[prost(uint32, tag = "1")]
    pub channel_id: u32,
    #[prost(uint32, tag = "2")]
    pub point_id: u32,
    #[prost(message, optional, tag = "3")]
    pub value: ::core::option::Option<CommandValue>,
    #[prost(map = "string, string", tag = "4")]
    pub context:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EncodeResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub encoded_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchReadRequest {
    /// 通道ID
    #[prost(uint32, tag = "1")]
    pub channel_id: u32,
    /// 要读取的点位
    #[prost(uint32, repeated, tag = "2")]
    pub point_ids: ::prost::alloc::vec::Vec<u32>,
    /// 连接参数
    #[prost(map = "string, string", tag = "3")]
    pub connection_params:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    /// 读取参数
    #[prost(map = "string, string", tag = "4")]
    pub read_params:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchReadResponse {
    #[prost(message, repeated, tag = "1")]
    pub points: ::prost::alloc::vec::Vec<PointData>,
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthStatus {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub details:
        ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// Generated client implementations.
pub mod protocol_plugin_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::http::Uri;
    use tonic::codegen::*;
    /// 插件服务接口
    #[derive(Debug, Clone)]
    pub struct ProtocolPluginClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ProtocolPluginClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ProtocolPluginClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ProtocolPluginClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<http::Request<tonic::body::BoxBody>>>::Error:
                Into<StdError> + Send + Sync,
        {
            ProtocolPluginClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 获取插件信息
        pub async fn get_info(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::PluginInfo>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/comsrv.plugin.v1.ProtocolPlugin/GetInfo");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "comsrv.plugin.v1.ProtocolPlugin",
                "GetInfo",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// 解析原始数据
        pub async fn parse_data(
            &mut self,
            request: impl tonic::IntoRequest<super::ParseRequest>,
        ) -> std::result::Result<tonic::Response<super::ParseResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/comsrv.plugin.v1.ProtocolPlugin/ParseData");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "comsrv.plugin.v1.ProtocolPlugin",
                "ParseData",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// 编码控制命令
        pub async fn encode_command(
            &mut self,
            request: impl tonic::IntoRequest<super::EncodeRequest>,
        ) -> std::result::Result<tonic::Response<super::EncodeResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/comsrv.plugin.v1.ProtocolPlugin/EncodeCommand",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "comsrv.plugin.v1.ProtocolPlugin",
                "EncodeCommand",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// 批量读取（主动轮询模式）
        pub async fn batch_read(
            &mut self,
            request: impl tonic::IntoRequest<super::BatchReadRequest>,
        ) -> std::result::Result<tonic::Response<super::BatchReadResponse>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path =
                http::uri::PathAndQuery::from_static("/comsrv.plugin.v1.ProtocolPlugin/BatchRead");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "comsrv.plugin.v1.ProtocolPlugin",
                "BatchRead",
            ));
            self.inner.unary(req, path, codec).await
        }
        /// 健康检查
        pub async fn health_check(
            &mut self,
            request: impl tonic::IntoRequest<super::Empty>,
        ) -> std::result::Result<tonic::Response<super::HealthStatus>, tonic::Status> {
            self.inner.ready().await.map_err(|e| {
                tonic::Status::new(
                    tonic::Code::Unknown,
                    format!("Service was not ready: {}", e.into()),
                )
            })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/comsrv.plugin.v1.ProtocolPlugin/HealthCheck",
            );
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new(
                "comsrv.plugin.v1.ProtocolPlugin",
                "HealthCheck",
            ));
            self.inner.unary(req, path, codec).await
        }
    }
}
